# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQK
  mysql-user: dXNlcgo=
  mysql-password: cGFzc3dvcmQK