---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: {{ .Values.service.selector.app }}
