replicaCount: 1

image:
  repository: mysql
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "5.6"

service:
  type: ClusterIP
  port: 3306
  selector:
    app: mysql

namespace:
  name: wordpress


